### ISSUE TITLE
The 'Example Setups' section is listed in pantheon, not besu.

### ISSUE THREAD

**Issue by pcmola** [Alethio/ethereum-lite-explorer#79] opened 2020-11-05 22:00 UTC
The 'Example Setups' section is listed in pantheon, not besu.

There seems to be a need to modify a few links as well.
Currently, it all leads to a 404 not found page.

**Comment by NicolasMassart** [comment] 2020-11-06 09:09
Link to https://besu.hyperledger.org/en/stable/HowTo/Deploy/Lite-Block-Explorer/ would be the best I guess

**Comment by pcmola** [comment] 2020-11-10 20:08
Thanks for answering.

There seems to be a misunderstanding because I left out what the wrong link is.
There are two places in README.md where links are incorrectly connected.

1.
`First of all, if you do not have it, [download and install Pantheon stable release](https://docs.pantheon.pegasys.tech/en/stable/Installation/Install-Binaries/).`
--> I think this can be done by linking here.
https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Installation-Options/Install-Binaries/

2.
 `For more information about these options, refer to the [Pantheon CLI   ##reference](https://docs.pantheon.pegasys.tech/en/stable/Reference/Pantheon-CLI-Syntax/)).`
--> I'm not sure how to fix this.

**Comment by NicolasMassart** [comment] 2020-11-12 13:55
I think you should completely remove all instructions about the way to dun the node and just link to the link I provided.
Like:

```
#### With Besu

This is a great way to use a full featured client, and to see how the explorer works with a private network.

Refer to [Besu Light Explorer HowTo](https://besu.hyperledger.org/en/stable/HowTo/Deploy/Lite-Block-Explorer/ ) to configure your node and explorer.
```

and that's it, so you don't have to maintain a duplicate of the doc and leave this to Besu team.

**Comment by pcmola** [comment] 2020-11-13 09:38
You are right.
I made a pull request based on your advice.
Thank you.

**Comment by tzapu** [comment] 2020-11-13 12:25
hey guys, i merged this as for some reason i still have access, but please bare in mind there is no more Alethio and no active maintainer of this stuff as far as i m aware.

thank you for using it tho 🥇

**Comment by NicolasMassart** [comment] 2020-11-13 13:23
Yes we sadly know 😞

**Closed** 2020-11-13 16:18 UTC

**Comment by Shednandezstore** [comment] 2023-07-30 11:49
0x3986382696b7206628d9e3711e5d5e2a804f23e56100cc9798feaa676a4d1630
